### ISSUE TITLE
The gradle build is broken - classes are not being resolved

### ISSUE THREAD

**Issue by ddelponte** [grails/grails-doc#154]
After following the instructions outlined at:  https://github.com/grails/grails-doc I receive the following errors. ?

Groovy-Guy:grails-doc deandelponte$ ./gradlew docs
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:fetchGrailsSource
Downloading Grails source code. If you already have a copy of the Grails source code checked out you can avoid this download by setting the grails.home system property to point to your local copy of the source. See README.txt for more information.
Grails source code has been downloaded to build/checkout/grails-src
:apiDocs
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:grails.core.ROOT:grails-async:compileJava UP-TO-DATE
:grails.core.ROOT:grails-async:processResources UP-TO-DATE
:grails.core.ROOT:grails-async:classes
:grails.core.ROOT:grails-async:jar UP-TO-DATE
:grails.core.ROOT:grails-bootstrap:compileJava UP-TO-DATE
:grails.core.ROOT:grails-bootstrap:processResources UP-TO-DATE
:grails.core.ROOT:grails-bootstrap:classes
:grails.core.ROOT:grails-bootstrap:compileUaaJava UP-TO-DATE
:grails.core.ROOT:grails-bootstrap:compileUaaGroovy
startup failed:
/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 26: unable to resolve class org.codehaus.groovy.grails.resolve.DependencyManager
 @ line 26, column 1.
   import org.codehaus.groovy.grails.resolve.DependencyManager
   ^

/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 19: unable to resolve class grails.util.BuildSettings
 @ line 19, column 1.
   import grails.util.BuildSettings
   ^

/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 18: unable to resolve class grails.build.logging.GrailsConsole
 @ line 18, column 1.
   import grails.build.logging.GrailsConsole
   ^

/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 20: unable to resolve class grails.util.PluginBuildSettings
 @ line 20, column 1.
   import grails.util.PluginBuildSettings
   ^

/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 25: unable to resolve class org.codehaus.groovy.grails.plugins.GrailsPluginInfo
 @ line 25, column 1.
   import org.codehaus.groovy.grails.plugins.GrailsPluginInfo
   ^

5 errors

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':grails-bootstrap:compileUaaGroovy'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 41.326 secs
Groovy-Guy:grails-doc deandelponte$ ./gradlew --stacktrace  docs
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:fetchGrailsSource
Downloading Grails source code. If you already have a copy of the Grails source code checked out you can avoid this download by setting the grails.home system property to point to your local copy of the source. See README.txt for more information.
Grails source code has been downloaded to build/checkout/grails-src
:apiDocs
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:grails.core.ROOT:grails-async:compileJava UP-TO-DATE
:grails.core.ROOT:grails-async:processResources UP-TO-DATE
:grails.core.ROOT:grails-async:classes
:grails.core.ROOT:grails-async:jar UP-TO-DATE
:grails.core.ROOT:grails-bootstrap:compileJava UP-TO-DATE
:grails.core.ROOT:grails-bootstrap:processResources UP-TO-DATE
:grails.core.ROOT:grails-bootstrap:classes
:grails.core.ROOT:grails-bootstrap:compileUaaJava UP-TO-DATE
:grails.core.ROOT:grails-bootstrap:compileUaaGroovy
startup failed:
/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 26: unable to resolve class org.codehaus.groovy.grails.resolve.DependencyManager
 @ line 26, column 1.
   import org.codehaus.groovy.grails.resolve.DependencyManager
   ^

/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 19: unable to resolve class grails.util.BuildSettings
 @ line 19, column 1.
   import grails.util.BuildSettings
   ^

/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 18: unable to resolve class grails.build.logging.GrailsConsole
 @ line 18, column 1.
   import grails.build.logging.GrailsConsole
   ^

/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 20: unable to resolve class grails.util.PluginBuildSettings
 @ line 20, column 1.
   import grails.util.PluginBuildSettings
   ^

/Users/deandelponte/code/grails-doc/build/checkout/grails-src/grails-bootstrap/src/uaa/groovy/org/codehaus/groovy/grails/cli/support/UaaEnabler.groovy: 25: unable to resolve class org.codehaus.groovy.grails.plugins.GrailsPluginInfo
 @ line 25, column 1.
   import org.codehaus.groovy.grails.plugins.GrailsPluginInfo
   ^

5 errors

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':grails-bootstrap:compileUaaGroovy'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':grails-bootstrap:compileUaaGroovy'.
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:68)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
  at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:34)
  at org.gradle.api.internal.changedetection.CacheLockHandlingTaskExecuter$1.run(CacheLockHandlingTaskExecuter.java:34)
  at org.gradle.cache.internal.DefaultCacheAccess$2.create(DefaultCacheAccess.java:200)
  at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:172)
  at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:198)
  at org.gradle.cache.internal.DefaultPersistentDirectoryStore.longRunningOperation(DefaultPersistentDirectoryStore.java:111)
  at org.gradle.api.internal.changedetection.DefaultTaskArtifactStateCacheAccess.longRunningOperation(DefaultTaskArtifactStateCacheAccess.java:83)
  at org.gradle.api.internal.changedetection.CacheLockHandlingTaskExecuter.execute(CacheLockHandlingTaskExecuter.java:32)
  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:55)
  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:41)
  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:52)
  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:42)
  at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:247)
  at org.gradle.execution.DefaultTaskGraphExecuter.executeTask(DefaultTaskGraphExecuter.java:192)
  at org.gradle.execution.DefaultTaskGraphExecuter.doExecute(DefaultTaskGraphExecuter.java:177)
  at org.gradle.execution.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:83)
  at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:36)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
  at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
  at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
  at org.gradle.api.internal.changedetection.TaskCacheLockHandlingBuildExecuter$1.run(TaskCacheLockHandlingBuildExecuter.java:31)
  at org.gradle.cache.internal.DefaultCacheAccess$1.create(DefaultCacheAccess.java:111)
  at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:126)
  at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:109)
  at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:103)
  at org.gradle.api.internal.changedetection.DefaultTaskArtifactStateCacheAccess.useCache(DefaultTaskArtifactStateCacheAccess.java:79)
  at org.gradle.api.internal.changedetection.TaskCacheLockHandlingBuildExecuter.execute(TaskCacheLockHandlingBuildExecuter.java:29)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
  at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
  at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
  at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:110)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:78)
  at org.gradle.api.tasks.GradleBuild.build(GradleBuild.java:112)
  at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:196)
  at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:102)
  at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:99)
  at org.gradle.api.tasks.GradleBuild_Decorated.invokeMethod(Unknown Source)
  at org.gradle.util.ReflectionUtil.invoke(ReflectionUtil.groovy:23)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$4.execute(AnnotationProcessingTaskFactory.java:150)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$4.execute(AnnotationProcessingTaskFactory.java:145)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:477)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:466)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:60)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
  at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:34)
  at org.gradle.api.internal.changedetection.CacheLockHandlingTaskExecuter$1.run(CacheLockHandlingTaskExecuter.java:34)
  at org.gradle.cache.internal.DefaultCacheAccess$2.create(DefaultCacheAccess.java:200)
  at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:172)
  at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:198)
  at org.gradle.cache.internal.DefaultPersistentDirectoryStore.longRunningOperation(DefaultPersistentDirectoryStore.java:111)
  at org.gradle.api.internal.changedetection.DefaultTaskArtifactStateCacheAccess.longRunningOperation(DefaultTaskArtifactStateCacheAccess.java:83)
  at org.gradle.api.internal.changedetection.CacheLockHandlingTaskExecuter.execute(CacheLockHandlingTaskExecuter.java:32)
  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:55)
  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:41)
  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:52)
  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:42)
  at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:247)
  at org.gradle.execution.DefaultTaskGraphExecuter.executeTask(DefaultTaskGraphExecuter.java:192)
  at org.gradle.execution.DefaultTaskGraphExecuter.doExecute(DefaultTaskGraphExecuter.java:177)
  at org.gradle.execution.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:83)
  at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:36)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
  at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
  at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
  at org.gradle.api.internal.changedetection.TaskCacheLockHandlingBuildExecuter$1.run(TaskCacheLockHandlingBuildExecuter.java:31)
  at org.gradle.cache.internal.DefaultCacheAccess$1.create(DefaultCacheAccess.java:111)
  at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:126)
  at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:109)
  at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:103)
  at org.gradle.api.internal.changedetection.DefaultTaskArtifactStateCacheAccess.useCache(DefaultTaskArtifactStateCacheAccess.java:79)
  at org.gradle.api.internal.changedetection.TaskCacheLockHandlingBuildExecuter.execute(TaskCacheLockHandlingBuildExecuter.java:29)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
  at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
  at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
  at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:110)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:78)
  at org.gradle.launcher.cli.RunBuildAction.execute(RunBuildAction.java:42)
  at org.gradle.launcher.cli.RunBuildAction.execute(RunBuildAction.java:28)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
  at org.gradle.launcher.exec.ExceptionReportingAction.execute(ExceptionReportingAction.java:31)
  at org.gradle.launcher.exec.ExceptionReportingAction.execute(ExceptionReportingAction.java:20)
  at org.gradle.launcher.Main.doAction(Main.java:48)
  at org.gradle.launcher.exec.EntryPoint.run(EntryPoint.java:45)
  at org.gradle.launcher.Main.main(Main.java:39)
  at org.gradle.launcher.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
  at org.gradle.launcher.ProcessBootstrap.run(ProcessBootstrap.java:32)
  at org.gradle.launcher.GradleMain.main(GradleMain.java:24)
  at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
  at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:47)
  Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
  at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:112)
  at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:39)
  at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:52)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  at org.gradle.messaging.remote.internal.TypeCastDispatch.dispatch(TypeCastDispatch.java:30)
  at org.gradle.messaging.remote.internal.WorkerProtocol.handleIncoming(WorkerProtocol.java:53)
  at org.gradle.messaging.remote.internal.WorkerProtocol.handleIncoming(WorkerProtocol.java:31)
  at org.gradle.messaging.remote.internal.ProtocolStack$ProtocolStage.handleIncoming(ProtocolStack.java:167)
  at org.gradle.messaging.remote.internal.ProtocolStack$BottomStage.handleIncoming(ProtocolStack.java:277)
  at org.gradle.messaging.remote.internal.ProtocolStack$BottomConnection$1.run(ProtocolStack.java:299)
  at org.gradle.messaging.remote.internal.ProtocolStack$ExecuteRunnable.dispatch(ProtocolStack.java:120)
  at org.gradle.messaging.remote.internal.ProtocolStack$ExecuteRunnable.dispatch(ProtocolStack.java:116)
  at org.gradle.messaging.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:132)
  at org.gradle.messaging.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:33)
  at org.gradle.messaging.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:72)
  at org.gradle.messaging.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:66)

BUILD FAILED

**Comment by guramritpal-jft** [comment]
@pledbrook  @ddelponte   What is the status of this issue...?  Is it Solved.?

**Comment by hakanernam** [comment]
I freshly forked and let it pull in grails sources when building. Seemed working but got NPE after a while.

| Grails Version: 3.1.0.M3
| Groovy Version: 2.4.5
| JVM Version: 1.8.0_66

```
truncated...

[ant:groovydoc] Resource org/codehaus/groovy/tools/groovy.ico not found so skipped
:grails-web-sitemesh:groovydoc (Thread[main,5,main]) completed. Took 6.586 secs.
:grails-web-taglib:groovydoc (Thread[main,5,main]) started.
:grails-web-taglib:groovydoc
Executing task ':grails-web-taglib:groovydoc' (up-to-date check took 0.024 secs) due to:
  No history is available.
[ant:groovydoc] Resource org/codehaus/groovy/tools/groovy.ico not found so skipped
:grails-web-taglib:groovydoc (Thread[main,5,main]) completed. Took 5.098 secs.
:grails-web-url-mappings:groovydoc (Thread[main,5,main]) started.
:grails-web-url-mappings:groovydoc
Executing task ':grails-web-url-mappings:groovydoc' (up-to-date check took 0.027 secs) due to:
  No history is available.
[ant:groovydoc] Resource org/codehaus/groovy/tools/groovy.ico not found so skipped
:grails-web-url-mappings:groovydoc (Thread[main,5,main]) completed. Took 13.599 secs.

BUILD SUCCESSFUL

Total time: 16 mins 27.778 secs
Stopped 2 compiler daemon(s).
:copyApiDocs
:publishGuide
<span class="error">Exception</span>: org.radeox.filter.MacroFilter@22e813fc
java.lang.NullPointerException
	at org.radeox.macro.parameter.BaseMacroParameter.insertValue(BaseMacroParameter.java:136)
	at org.radeox.macro.parameter.BaseMacroParameter.split(BaseMacroParameter.java:121)
	at org.radeox.macro.parameter.BaseMacroParameter.setParams(BaseMacroParameter.java:52)
	at org.radeox.filter.MacroFilter.handleMatch(MacroFilter.java:96)
	at org.radeox.filter.regex.RegexTokenFilter$1.handleMatch(RegexTokenFilter.java:90)
	at org.radeox.regex.JdkMatcher.substitute(JdkMatcher.java:42)
	at org.radeox.filter.regex.RegexTokenFilter.filter(RegexTokenFilter.java:88)
	at org.radeox.filter.MacroFilter.handleMatch(MacroFilter.java:107)
	at org.radeox.filter.regex.RegexTokenFilter$1.handleMatch(RegexTokenFilter.java:90)
	at org.radeox.regex.JdkMatcher.substitute(JdkMatcher.java:42)
	at org.radeox.filter.regex.RegexTokenFilter.filter(RegexTokenFilter.java:88)
	at org.radeox.filter.FilterPipe.filter(FilterPipe.java:190)
	at org.radeox.engine.BaseRenderEngine.render(BaseRenderEngine.java:109)
	at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
```

**Comment by hakanernam** [comment]
Still, I found assembled HTML documents in build/docs. And the message:

```
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[ant:echo] Built user manual at grails-doc/build/docs/index.html
:publishPdf
:docs

BUILD SUCCESSFUL
```

So it seems successful, except the NPE.

**Comment by jameskleeh** [comment]
Instructions have changed since the change to asciidoc
